const mongoose = require('mongoose');
const fs = require('fs');
const csv = require('csv-parser');
const WasteItem = require('./models/WasteItem');
require('dotenv').config();

// Path to the CSV file generated by Python
const CSV_PATH = '../ai-engine/data/synthetic_waste_data.csv';

const seedDB = async () => {
  try {
    // 1. Connect to MongoDB
    console.log('🔌 Connecting to MongoDB...');
    await mongoose.connect(process.env.MONGO_URI);
    console.log('✅ Connected!');

    // 2. Clear existing data (optional, prevents duplicates)
    console.log('🧹 Clearing old data...');
    await WasteItem.deleteMany({});

    // 3. Read CSV and Insert
    const results = [];
    console.log('📂 Reading CSV data...');

    fs.createReadStream(CSV_PATH)
      .pipe(csv())
      .on('data', (data) => {
        // Convert numbers from strings to floats
        results.push({
          ...data,
          quantity_kg: parseFloat(data.quantity_kg),
          demand_index: parseFloat(data.demand_index),
          price_per_unit_lkr: parseFloat(data.price_per_unit_lkr),
          total_value_lkr: parseFloat(data.total_value_lkr),
          date_listed: new Date(data.date_listed)
        });
      })
      .on('end', async () => {
        console.log(`🚀 Uploading ${results.length} items to Cloud...`);
        await WasteItem.insertMany(results);
        console.log('🎉 SUCCESS: Database seeded!');
        process.exit();
      });

  } catch (err) {
    console.error('❌ Error:', err);
    process.exit(1);
  }
};

seedDB();
